config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'

  resources :users

  resources :password_resets

  resources :letters do
    patch 'add_or_subtract_snippet'
    get 'retrieve_letter'
    patch 'update_positions'
    patch 'build_snippet_letter'

    collection do
      get 'letter_admin'
      post 'create_with_snippet'
      post 'create_with_quiz'
    end

  end

  resources :snippets do

    collection do
      get 'snippet_admin'
    end

  end

  resources :authors
  resources :letter_orders do
    member do
      get 'deliver_as_email'
      get 'checkout'
      post 'charge_create'
      get 'deliver_as_snail'
      get 'cancel'
    end
  end

  
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  post 'sessions' => 'sessions#create'

  get '/auth/:provider/callback' => 'sessions#omniauth_create'
  get '/signout' => 'sessions#omniauth_destroy', :as => :signout

  get 'switch' => 'letters#switch_workspace'
  get 'dashboard' => 'users#dashboard'

end

app/models/letter.rb
class Letter < ActiveRecord::Base
  belongs_to :author
  has_many :letter_orders
  has_many :users, through: :letter_orders
  has_many :letter_snippets
	has_many :snippets, through: :letter_snippets
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  load_and_authorize_resource
  layout 'workspace'

  def index
    @letters = current_user.letters.where("content is Not NULL")
  end

  def show
    @offset = params[:offset].to_i
    @direction = params[:direction]
    @current_letter = Letter.where("author_id is Not NULL").limit(1).offset(@offset).first
    @next_letter = Letter.where("author_id is Not NULL").limit(1).offset(@offset + 1).first
    @current_user_id = current_user.id.to_s
    @current_letter_id = @current_letter.id.to_s

    if @offset == 0
      @previous_letter = nil
    else
      @previous_letter = Letter.limit(1).offset(@offset - 1).first
    end
  end

  def create
    @letter = Letter.new(letter_params)
    if @letter.save
      gflash notice: "Your letter has been created successfully!"
      redirect_to :back
    else
      gflash notice: "Something went wrong tryign to save your letter. Please try again."
      redirect_to :back
    end
  end

  def create_with_snippet
    @letter = Letter.find(params[:letter][:letter_id])
    @snippet = Snippet.find(params[:letter][:snippet_id])
    letter_snippet = LetterSnippet.new letter: @letter, snippet: @snippet, position: 1
    letter_snippet.save
  end

  def add_or_subtract_snippet
    letter_id = params[:letter_id].to_i
    snippet_id = params[:snippet][:snippet_id].to_i
    @snippet = Snippet.find(snippet_id)
    if params[:snippet][:checked] == "false"
      @letter = Letter.find(letter_id)
      snippet_count = @letter.snippets.count
      letter_snippet = LetterSnippet.new letter: @letter, snippet: @snippet, position: snippet_count + 1
      letter_snippet.save
    else
      @letter = Letter.find(letter_id)
      @letter.snippets.delete(@snippet)
      @letter.save
    end
  end

  def update_positions
    JSON.parse(params[:Activity]).each_with_index do |incoming_data, index|
      letter_id = incoming_data['letter_id']
      snippet_id = incoming_data["snippet_id"]
      position = incoming_data["position"]
      letter_snippet = LetterSnippet.where("letter_id = ? AND snippet_id = ?", letter_id, snippet_id).first
      letter_snippet.position = position
      letter_snippet.save
    end
  end

  def create_with_quiz
    @letter = Letter.create
    current_user.save
    process_question_return_snippet(1, params[:question_1], @letter)
    process_question_return_snippet(2, params[:question_2], @letter)
    process_question_return_snippet(3, params[:question_3], @letter)
    process_question_return_snippet(4, params[:question_4], @letter)
    process_question_return_snippet(5, params[:question_5], @letter)
    build_quiz_letter(@letter)
  end

  def process_question_return_snippet(question, answer, letter)
    case question
    when 1
      if answer == "A"
        snippet = set_snippet(letter)
      elsif answer == "B"
        snippet = set_snippet(letter)
      else
      end
    when 2
      if answer == "A"
        snippet = set_snippet(letter)
      elsif answer == "B"
        snippet = set_snippet(letter)
      else
        snippet = set_snippet(letter)
      end
    when 3
      if answer == "A"
        snippet = set_snippet(letter)
      elsif answer == "B"
        snippet = set_snippet(letter)
      else
        snippet = set_snippet(letter)
      end
    when 4
      if answer == "A"
        snippet = set_snippet(letter)
      elsif answer == "B"
        snippet = set_snippet(letter)
      else
        snippet = set_snippet(letter)
      end
    else
      if answer == "A"
        snippet = set_snippet(letter)
      elsif answer == "B"
        snippet = set_snippet(letter)
      else
        snippet = set_snippet(letter)
      end
    end
  end

  def retrieve_letter
    @letter = Letter.find(params[:letter_id])
  end

  def switch_workspace
    @workspace = params[:workspace]
    @authors = Author.all
    @images = ['Book.png', 'Communication.png', 'Compass.png', 'Cut.png', 'Download.png', 'Envelope.png', 'Eye.png', 'Hourglass.png', 'Key.png', 'Lighthouse.png', 'Locator.png', 'map_with_locator.png', 'Mountain.png', 'Note.png', 'Pencil.png', 'Picture.png', 'Search.png', 'sound_wave.png', 'Volume.png']
    if @workspace == "full_letter_workspace"
      @offset = 0
      @current_letter = Letter.where("author_id is Not NULL").first
      @previous_letter = nil
      @next_letter = Letter.where("author_id is Not NULL").limit(1).offset(0)[0]
    elsif @workspace == "snippet_workspace"
      @authors = Author.joins(:snippets).where('snippets is not null').uniq
      @current_letter = Letter.create
    else
      @current_letter = Letter.new
    end
  end

  def set_snippet(letter)
    snippet = nil
    loop do
      snippet = Snippet.all.sample
      break unless letter.snippets.include? snippet 
    end
    snippet
  end

  def build_snippet_letter
    @letter = Letter.find(params[:letter_id])
    letter_content = ''
    @letter.snippets.by_position.each do |snippet|
      letter_content += " #{snippet.content}"
    end
    @letter.content = letter_content
    @letter.save
    render nothing: true
  end

  def build_quiz_letter(letter)
    letter_content = ''
    @letter.snippets.each do |snippet|
      letter_content += " #{snippet.content}"
    end
    @letter.content = letter_content
    @letter.save
  end


  # add delete functionality if user clicks on fade/close (rather than submitting next form)
  # def add_to_user
  #   @letter = Letter.find(params[:letter_id])
  #   @user = User.find(params[:letter][:user_id])
  #   @user.letters << @letter
  #   if @user.save
  #     render plain: "1"
  #   else
  #     render plain: "0"
  #   end
  # end

  private

  def letter_params 
    params.require(:letter).permit(:content, :author_id, :user_id)
  end

end

app/views/letters/_content.html.haml
%br
%h3.centered.letter_data{data: {"letter-id" => @current_letter.id, "user-id" => current_user.id}}
  = @current_letter.author.first_name
  = @current_letter.author.last_name
%br

.letter_text
  = simple_format(@current_letter.content)
%br

 

app/views/letters/_letter_genie_workspace.html.haml
.pad_the_top
= link_to "Back", new_letter_path, class: "btn-primary btn workspace_back floating_nav"


.row
  .container
    .col-lg-10.col-md-10.col-lg-offset-1.col-md-offset-1.main_content
      %h2.centered.genie_title Cyrano de Robot
      %p.centered.pad Answer the following questions and our Cyrano-bot will generate a love letter to beat all love letters.
      .quiz_content.col-lg-8.col-md-8.col-sm-8.col-lg-offset-2.col-md-offset-2.col-sm-offset-2
      
      
        = form_tag create_with_quiz_letters_path, remote: true do
          .part_1
            %h3 What word best describes your desired letter?
            .answer_holder.text-center
              .btn-group.center_this{"data-toggle" => "buttons"}
                %label.btn.btn-primary.quiz_answer.red_button.first
                  = radio_button_tag :question_1, "A"
                  Poetic
                %label.btn.btn-primary.quiz_answer.red_button
                  = radio_button_tag :question_1, "B"
                  Passionate
                %label.btn.btn-primary.red_button
                  = radio_button_tag :question_1, "C"
                  Pathetic
          %br
          .part_1
            %h3 On a scale of 1-3, how flowery do you want your letter to be?
            .answer_holder.text-center
              .btn-group.center_this{"data-toggle" => "buttons"}
                %label.btn.btn-primary.quiz_answer.first.red_button
                  = radio_button_tag :question_2, "A"
                  1
                %label.btn.btn-primary.quiz_answer.red_button
                  = radio_button_tag :question_2, "B"
                  2
                %label.btn.btn-primary.red_button
                  = radio_button_tag :question_2, "C"
                  3
          %br
          .part_1
            %h3 How long have you known this love letter's recipient?
            %br
            .answer_holder.text-center
              .btn-group.centered{"data-toggle" => "buttons"}
                %label.btn.btn-primary.quiz_answer.first.red_button
                  = radio_button_tag :question_3, "A"
                  Under 6 wks
                %label.btn.btn-primary.quiz_answer.red_button
                  = radio_button_tag :question_3, "B"
                  6 wks to a year
                %label.btn.btn-primary.red_button
                  = radio_button_tag :question_3, "C"
                  Forever
          %br
          .part_1
            %h3 Which of the following flowers best represents your love?
            %br
              .answer_holder.text-center
                .btn-group.center_this{"data-toggle" => "buttons"}
                  %label.btn.btn-primary.quiz_answer.first.red_button
                    = radio_button_tag :question_4, "A"
                    Red Roses
                  %label.btn.btn-primary.quiz_answer.red_button
                    = radio_button_tag :question_4, "B"
                    Black Roses
                  %label.btn.btn-primary.red_button
                    = radio_button_tag :question_4, "C"
                    Lilies
          %br
          .part_1
            %h3 What do you most want to communicate through your letter?
            %br
            .answer_holder.text-center
              .btn-group{"data-toggle" => "buttons"}
                %label.btn.btn-primary.quiz_answer.first.red_button
                  = radio_button_tag :question_5, "A"
                  Your feelings.
                %label.btn.btn-primary.quiz_answer.red_button
                  = radio_button_tag :question_5, "B"
                  Your commitment.
                %label.btn.btn-primary.red_button
                  = radio_button_tag :question_5, "C"
                  Your amusement.
          %br
          %br
          = submit_tag "Submit", :class => 'btn btn-default btn-block btn-danger'



        .send_letter_modal.modal_custom
          = render "letters/send_letter_modal", letter: @current_letter

app/views/letters/_letter_nav.html.haml
- if previous_letter.present?
  = link_to "Previous", letter_path(previous_letter, offset: offset - 1, direction: "previous"), remote: true, class: "btn-default btn-primary btn direction_button"
- else
  = link_to "Previous", root_path, class: "btn-default btn btn-primary  disabled direction_button"

- if next_letter.present?
  = link_to "Next", letter_path(next_letter, offset: offset + 1, direction: "next"), remote: true, class: "btn-default btn btn-primary direction_button"
- else
  = link_to "Next", root_path, class: "btn-default btn-primary btn disabled direction_button"

app/views/letters/_quiz_letter.html.haml
%h1
  Dearest [Recipient Name Here],

%p
  = simple_format(letter.content)
%p
  Love,
%p 
  Your Name Here!

%br

= link_to "Review and Send Letter", new_letter_path, class: "btn-primary btn btn-block send_letter_button col-lg-12 col-md-12"

.send_letter_modal.modal_custom
  = render "letters/send_letter_modal", letter: letter

app/views/letters/_snippet_letter_list.html.haml
%p 
	Drag your snippets into the order you want them to appear in your letter. 
	= link_to "Send", root_path, class: "btn-warning btn send_snippet_letter_button"
%br
.col-lg-8.col-md-8.col-sm-8.col-lg-offset-2.col-md-offset-2.col-sm-offset-2
	%ol.sortable
		- letter.snippets.by_position.each do |snippet|
			%li.well.center_width{data: { "snippet-id" => "#{snippet.id}", "letter-id" => "#{letter.id}"}}= snippet.content

	= link_to "Review and Send Letter", root_path, class: "btn-warning btn btn-block send_snippet_letter_button col-lg-12 col-md-12"

:javascript
	$(".sortable").sortable();

app/views/letters/_snippet_list.html.haml
- author.snippets.each do |snippet|
  .holder
    .col-lg-2.col-md-2.col-sm-2
      .btn-group{"data-toggle" => "buttons"}
        %label.btn.btn-primary.answer.snippet_button
          - if letter.snippets.include?(snippet)
            = check_box_tag snippet.id, snippet.id, letter.snippets.include?(snippet), class: 'checkbox', data: { "snippet-id" => snippet.id }
            Remove
          - else
            = check_box_tag snippet.id, snippet.id, letter.snippets.include?(snippet), class: 'checkbox', data: { "snippet-id" => snippet.id }
            Add

    .col-lg-10.col-md-10.col-sm-10
      %h4.snippet_margin= snippet.content  

    %br
    %br
    %br

app/views/letters/_snippet_workspace.html.haml
.pad_the_top
%h2.centered.mash_title Letter Mash
= link_to "Back", new_letter_path, class: "btn-primary btn workspace_back floating_nav"


.row
  .container
    .letter_nav
      = link_to "Choose Snippets", root_path, class: "btn-default btn snippet_view widen btn-primary"
      = link_to "Arrange Letter", root_path, class: "btn-default btn letter_view widen btn-primary"
      %br
      %br
      

      .letter_view_workspace
        Add some snippets and then sort them here.

      .snippet_view_workspace{ id: 'false', data: {"letter-id" => @current_letter.id } }
        .col-lg-8.col-md-8.col-sm-8.col-lg-offset-2.col-md-offset-2.col-sm-offset-2
          - @authors.each do |author|
            .row.snippet_title
              %table
                %thead
                  %th
                    %span.glyphicon.glyphicon-user.author_icon
                  %th 
                    %h3.inline_title.author_name= "#{author.first_name} #{author.last_name}'s Snippets"
              
            .row.author_snippets{id: "author-id-#{author.id}"}
              - author.snippets.each do |snippet|
                .holder
                  .col-lg-2.col-md-2.col-sm-2
                    .btn-group{"data-toggle" => "buttons"}
                      %label.btn.btn-primary.answer.snippet_button
                        = check_box_tag snippet.id, snippet.id, false, class: 'checkbox', data: { "snippet-id" => snippet.id }
                        Add

                  .col-lg-10.col-md-10.col-sm-10
                    %h4.snippet_margin= snippet.content  

                %br
                %br
                %br
            %br
            %br
            %br
          %br

.send_letter_modal.modal_custom
  = render "letters/send_letter_modal", letter: @current_letter



         
                

    

app/views/letters/create_with_quiz.js.erb
$('.quiz_content').html('');
$('.quiz_content').html("<%= escape_javascript render(:partial => 'letters/quiz_letter', :locals => { :letter => @letter })%>");

app/views/letters/letter_admin.html.haml
.container
  %h1 Letter Admin

  %br


  .col-lg-6.col-md-6
    %h4 Enter a Letter
    = form_for Letter.new do |f|

      = f.label :author
      = f.select :author_id, Author.all.collect {|a| [ "#{a.first_name} #{a.last_name}", a.id ] }, class: 'form-control'
      %br
      = f.label :content
      = f.text_area :content, :cols => 40, :rows => 15, class: 'form-control'
      %br
      = f.submit

  .col-lg-6.col-md-6
    %h4 Enter an Author
    = form_for Author.new do |f|
      = f.label :first_name
      = f.text_field :first_name, class: 'form-control'
      %br
      = f.label :last_name
      = f.text_field :last_name, class: 'form-control'
      %br
      = f.label :bio
      = f.text_area :bio, class: 'form-control'
      %br
      = f.label :author_image
      = f.file_field :author_image, class: 'form-control'
      %br
      = f.submit

%br
%br

app/views/letters/retrieve_letter.js.erb
$('.letter_view_workspace').html('');
$('.letter_view_workspace').html("<%= escape_javascript render(:partial => 'letters/snippet_letter_list', :locals => { :letter => @letter })%>");

app/views/letters/show.js.erb
var direction = '<%= escape_javascript @direction %>';
var current_letter = '<%= escape_javascript @current_letter_id %>';
var current_user = '<%= escape_javascript @current_user_id %>';

var first_direction = ""
var second_direction = ""

if (direction == "next") {
  first_direction = "right"
  second_direction = "left"
} else {
  first_direction = "left"
  second_direction = "right"
};

$('.letter_nav').html("");
$('.letter_nav').html('<%= escape_javascript render(:partial => "letters/letter_nav", :locals => { :offset => @offset, :next_letter => @next_letter, :previous_letter => @previous_letter})%>');

$('.letter_content').hide("slide", { direction: first_direction }, 600, function() {

  $('#letter_order_letter_id').val(current_letter);
  $('#letter_order_user_id').val(current_user);
  $('.letter_content').html("");
  $('.letter_content').html('<%= escape_javascript render(:partial => "letters/content", :locals => { :current_letter => @current_letter })%>');

});

$('.letter_content').show("slide", { direction: second_direction }, 600)

app/views/letters/snippet_admin.html.haml
.container
  %h1 Snippet Admin

  %br


  .col-lg-6.col-md-6
    %h4 Enter a Snippet
    = form_for Snippet.new do |f|

      = f.label :author
      = f.select :author_id, Author.all.collect {|a| [ "#{a.first_name} #{a.last_name}", a.id ] }, class: 'form-control'
      %br
      = f.label :content
      = f.text_area :content, :cols => 40, :rows => 15, class: 'form-control'
      %br
      = f.submit

  .col-lg-6.col-md-6
    %h4 Enter an Author
    = form_for Author.new do |f|
      = f.label :first_name
      = f.text_field :first_name, class: 'form-control'
      %br
      = f.label :last_name
      = f.text_field :last_name, class: 'form-control'
      %br
      = f.label :bio
      = f.text_area :bio, class: 'form-control'
      %br
      = f.label :author_image
      = f.file_field :author_image, class: 'form-control'
      %br
      = f.submit

%br
%br

app/views/letters/switch_workspace.js.erb
var workspace = '<%= escape_javascript @workspace %>';

if (workspace == "snippet_workspace") {
  $('.snippet_view_workspace').attr("data-letter-id","<%= @current_letter.id %>");
}



$('.main_content').hide("slide", { direction: "right" }, 800, function() {

  $('.main_content').html("");
  $('.workspace_background_image').css("background-image", '')
  $('.main_content').html('<%= escape_javascript render(:partial => "letters/#{@workspace}")%>');
  $('.workspace_background_image').css("background-image", '<%= asset_path("paper_it.png") %>')
  $('.workspace_buttons').fadeOut();
  
}).delay(300);


$('.main_content').show("slide", { direction: "left" }, 800, function() {
  
  $('.floating_nav').fadeIn('slow');

  if (workspace == "snippet_workspace") {
    <%= add_gritter("Choose the snippets you want to include, then arrange them in the order you want them to appear in your letter.", :title => "Instructions", :sticky => true) %>
  }

});